#!/bin/sh

#bcn, Bluetooth Connect
CONFIG="$HOME/.config/hypr/wofi/config"
STYLE="$HOME/.config/hypr/wofi/style.css"
COLORS="$HOME/.config/hypr/wofi/colors"

wofi_command="wofi --show dmenu \
			--prompt 'choose..'
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=600 --height=300 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

device_amount=$(bluetoothctl devices | wc -l)

if [[ $device_amount = 1 ]]; then
	MAC=$(bluetoothctl devices | awk {'print $2'})
		[ -z $MAC ] && MAC=NoDeviceFound # Prevents accidental disconnect error
else
	select=$(bluetoothctl devices | awk {'print $3'} | $wofi_command)
	MAC=$(bluetoothctl devices | grep $select | awk {'print $2'}) 
		[ -z $MAC ] && MAC=NoDeviceFound # Prevents accidental disconnect error
fi

connect=$(bluetoothctl info $MAC | grep Connected: | awk '{print $2}')
if [[ $connect = no ]]; then 
	notify-send "Attempting to connect to $select"
	bluetoothctl connect $MAC || notify-send "Failed to Connect"
elif [[ $connect = yes ]]; then
	notify-send "Attempting to disconnect $select"
	bluetoothctl disconnect $MAC 
fi